### ISSUE TITLE
Please, support tvOS 

### ISSUE THREAD

**Issue by Maxatma** [lobodart/CheatyXML#11]
Hi, is there a reason why can't u support tvOS.
Tried to add your awesome pod and got this: 
[!] The platform of the target `x` (tvOS 13) is not compatible with `CheatyXML (3.0.0)`, which does not support `tvOS`.

**Comment by lobodart** [comment]
Hi @Maxatma! Thanks for having pointed this out. I will have a look today 🙂

**Comment by lobodart** [comment]
@Maxatma Just added tvOS support (9.0 or later) 🎉
Just bump pod version to 3.1.0.
Feel free to report any issue you have!
Enjoy!

**Comment by Maxatma** [comment]
Thanks!
