### ISSUE TITLE
Minor warnings from CXMLParser.swift

### ISSUE THREAD

**Issue by ajackson2907** [lobodart/CheatyXML#5]
Hi,

Just pointing out the following warnings that are being shown by XCode 9.3.

![screen shot 2018-05-02 at 12 55 42](https://user-images.githubusercontent.com/21180663/39521965-98803238-4e08-11e8-8e30-1158b55c0003.png)

Thanks for the library,

Jacko

**Comment by lobodart** [comment]
Thanks for pointing this out. I'm on it 👍

**Comment by lobodart** [comment]
@Jacko1972 Sorry for the long wait! It is now fixed in the new version (2.2.0) 😃
Enjoy!
